README.md

Add badges for the conda packages.
Closes #30

README: add badges for conda-forge

---

conda-store-server/conda_store_server/server/templates/navigation.html

Closes #70 
It looks like this

add help button pointing to docs

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/templates/create.html
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/utils.py
conda-store-server/conda_store_server/worker/tasks.py

Adding support for namespaces

---

conda-store-server/conda_store_server/server/templates/base.html
conda-store-server/conda_store_server/server/templates/home.html

* added a pointer + tooltip
* fixed namespace field in the URL

improve usability of the docker button

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/utils.py
conda-store-server/conda_store_server/server/views/registry.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/worker/tasks.py
examples/docker/docker-compose.yaml

Also allow conda-store to keep track of all build artifacts so that UI reflects artifacts that are available.

Fixing docker registry protocol bits

---

docs/installation.md

Add default username/pw to docker instructions

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Adding pagination and support for search on packages

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/registry.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/worker/tasks.py

Closes https://github.com/Quansight/conda-store/issues/152
Wow that did require a lot of changes but it did simplify a lot of the queries so I think this is a win. Also greatly simplifies the mental model for conda-store tables. Involved a lot of refactoring of names.

Change database table relationship for build -> environment instead of build -> namespace

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Fix #151 Adding ability to filter packages by build along with adding build to api response

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Adding route for listing packages within build

---

conda-store-server/conda_store_server/server/views/api.py

Fix #158 get query count before applying limits to query

---

conda-store-server/conda_store_server/server/views/api.py

Fix #161 make sorting for conda packages stable

---

conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Closes #163
This required removing the jsonify bits from `paginated_api_response`

Fix #163 Adding distinct_on query to package rest api endpoint

---

conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Adding namespace to POST /api/v1/specification/

---

docs/administration.md
docs/contributing.md
docs/user_guide.md

Sorry for not combining into a single PR, but I found a few more.

Few more typos

---

conda-store-server/setup.py

Remove psycopg2 as a dependency in setup.py

---

conda-store-server/conda_store_server/server/views/api.py

Fixing bug with error creating environments via api endpoint

---

conda-store-server/conda_store_server/server/views/api.py

Fixing for when namespace does not exist in specification

---

docs/contributing.md

docs: add sample JSON payload

---

conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/views/api.py

Returning conda channel instead of id for gator UI

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/views/api.py

Post /api/v1/specification should return build id on success

---

conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py

Inconsistancy buildId vs build_id. Chose build_id to prefer the python approach

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/views/ui.py
docs/administration.md
tests/assets/conda_store_config.py

Adding ability to modify and validate specification

---

conda-store/Dockerfile
examples/docker/assets/conda_store_config.py
examples/docker/assets/condarc
examples/docker/assets/jupyterhub_config.py
examples/docker/docker-compose.yaml

Before starting, make sure you have adequately provisioned Docker. For reference, my Docker resources look like this:
git clone this repo, then:
```
cd conda-store/examples/docker
docker compose up --build 
```
This will take several minutes. Then open the following link in your browser:
http://localhost:8000
This will open JupyterHub. Login as test user:
user: test
password: test
Should take you to JupyterLab on port 8000. From there you can go to:
Settings > Conda Store Packages Manager
And play around with creating, deleting, cloning environments and adding, removing, updating packages from those environments.

Docker compose add gator

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml

Making conda package population independent from package builds

---

conda-store-server/conda_store_server/server/views/api.py

Account for None, "" values for namespace

---

.github/workflows/documentation.yaml
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml
docs/installation.md
examples/docker/assets/conda_store_config.py
examples/docker/assets/jupyter_notebook_config.py
examples/docker/assets/jupyterhub_config.py
examples/docker/docker-compose.yaml

Creating a conda solve api endpoint

---

conda-store-server/conda_store_server/app.py
flake.nix

Extract package name from included and required packages

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/environment.py
docs/administration.md
tests/assets/conda_store_config.py

Adding pypi package validation for required, included, and default

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/worker/tasks.py
docs/administration.md

Making the default filesystem namespace used configurable

---

conda-store-server/conda_store_server/server/auth.py
tests/e2e/cypress/integration/main.js

Redirect login to home page instead of user page

---

conda-store-server/conda_store_server/server/templates/home.html

Adds a searchbar on homepage for namespace/name filtering.

Adding searchbar for environments

---

conda-store-server/conda_store_server/server/auth.py
conda-store/Dockerfile
conda-store/conda_store/cli.py
examples/docker/assets/conda_store_config.py
examples/docker/assets/jupyterhub_config.py

Decrease build times and the fact that we are developing a successor to gator with conda-store-ui

Remove gator from the docker image

---

conda-store-server/Dockerfile
conda-store/Dockerfile
docker-compose.yaml
examples/docker-without-nfs/docker-compose.yaml
examples/docker/docker-compose.yaml

in Dockerfiles and docker-compose.yaml files

enforce user 1000 group 1000 #305

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/environment.py
docs/administration.md

Add option to allow all channels is empty

---

.github/workflows/tests.yaml
conda-store/conda_store/__main__.py
conda-store/conda_store/cli.py
conda-store/setup.cfg
docs/user_guide.md
tests/scripts/shebang.py

Feature motivated from https://gist.github.com/travisbhartwell/f972aab227306edfcfea

Adding shebang support for conda-store

---

conda-store-server/conda_store_server/server/templates/home.html
tests/e2e/cypress/integration/main.js

Fixes https://github.com/Quansight/conda-store/issues/288

feat: visually split Namespace and Name in UI

---

conda-store/Dockerfile
docs/contributing.md

Just adding a small warning for those developing on MacOS.

Add note for MacOS dev

---

conda-store-server/environment-dev.yaml
conda-store-server/setup.cfg
conda-store/setup.cfg
docs/conf.py
docs/contributing.md
docs/installation.md

- ✅ Closes #404
- ✅ Closes #406 
- 🧹 Hide the left sidebar on https://conda.store/en/latest/contributing.html
- 🧹 Remove some trailing spaces
Please squash-merge this PR when ready, for a clean commit-history. :)

Sphinx updates: Move to MyST, add copybutton

---

docs/_static/css/custom.css

Custom CSS for Swagger UI and dark mode

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/schema.py

This solves issue #413 by updating the schema and the according unpacking of those variables. 
cc: @dharhas @costrouc

Implement variable parsing for environments

---

conda-store-server/conda_store_server/build.py

use .get() when looking up keys in JSON column

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/worker/tasks.py
docs/administration.md

[](https://github.com/Quansight/conda-store/issues/421)(https://github.com/Quansight/conda-store/issues/421)

Adding configurable post_update_environment_build_hook

---

.github/workflows/docs.yaml
.github/workflows/tests.yaml

The docs actions occasionally fails likely due to several actions trying to upload at the same time.

Separating out into independant test for speed and minimize long runs

---

conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/templates/conda-store-ui.html
conda-store-server/conda_store_server/server/templates/navigation.html
conda-store-server/conda_store_server/server/views/__init__.py
conda-store-server/conda_store_server/server/views/conda_store_ui.py
conda-store-server/conda_store_server/server/views/ui.py
tests/test_playwright.py

Change the default ui to conda-store-ui

---

conda-store-server/conda_store_server/server/templates/conda-store-ui.html
conda-store-server/conda_store_server/server/templates/user.html
conda-store-server/hatch_build.py

These are small fixes to the main.js generated from compiling conda-store-ui and making the settings configurable. This is bound to break eventually.

Adding fixes for making conda-store-ui configurable from conda-store

---

.github/workflows/release.yaml
CHANGELOG.md

deploy images to quayio too

---

conda-store-server/conda_store_server/server/templates/conda-store-ui.html

Fix #462 : Green theme for conda-store UI

Fix #462 : Green theme for conda-store UI

---

conda-store-server/conda_store_server/server/app.py
conda-store-server/tests/test_traitlets.py
docs/administration.md

Finally adding tests for traitlets and adding the capability for adding arbitrary additional routes.

Adding tests that test traitlets for conda-store-server

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/alembic/versions/abd7248d5327_adding_a_settings_table.py
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/environment.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/templates/namespace.html
conda-store-server/conda_store_server/server/templates/setting.html
conda-store-server/conda_store_server/server/templates/user.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/tests/conftest.py
conda-store-server/tests/test_db_api.py
conda-store-server/tests/test_server.py
conda-store-server/tests/test_traitlets.py
tests/test_api.py

Large effort to create a central settings object that conda-store manages.

Adding global/namespace/environment settings with api/ui and tests

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/storage.py

Adding incremental updates to the logs.

Adding incremental updates to the logs

---

conda-store-server/conda_store_server/action/generate_conda_docker.py
conda-store-server/tests/test_actions.py
conda-store-server/tests/test_app_api.py

Change layered build to single layer.

Fixing docker builds temporarily by creating single image

---

SECURITY.md

📝 Add security policy

---

.github/workflows/deploy_docker_image.yaml
.github/workflows/release.yaml

Part of https://github.com/conda-incubator/conda-store/issues/514

Fixing vault role and paths

---

docs/installation.md

This PR fixes the login dummy instructions

Fix default login instructions

---

conda-store/conda_store/api.py
conda-store/conda_store/auth.py
conda-store/conda_store/utils.py
conda-store/tests/authenticated-token-tests.sh

Add trailing slash to avoid redirects

---

docs/contributing.md

This updates the release docs to reflect the current release process. 
This is part of issue https://github.com/conda-incubator/conda-store/issues/514

Update release docs to reflect pyproject.toml changes

---

.github/PULL_REQUEST_TEMPLATE.md

Fix some spelling errors in the PR template

---

LICENSE

Addresses #399 
- Updates license attribution after the move to conda-incubator

Update LICENSE attribution

---

docusaurus-docs/docusaurus.config.js
docusaurus-docs/src/pages/index.js

Addresses #397
- Explains the three conda-store projects on the homepage
https://github.com/conda-incubator/conda-store/assets/33131404/150d1bf2-6b5c-4ef2-a050-4084f0c40ce9

DOC - Update homepage to include project details

---

.github/ISSUE_TEMPLATE/new-release.md
docusaurus-docs/community/release.md

Fixes #585 
- Updates the release docs
- Adds a release issue template

MAINT - Update release docs and add issue template

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/dependencies.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/metrics.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/environment-dev.yaml
conda-store-server/environment-macos-dev.yaml
conda-store-server/tests/test_actions.py
tests/test_api.py

Bug fix: use context manager for Sessions

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/general-issue.yml
.github/ISSUE_TEMPLATE/new-release.md

I noticed all the general issues were labelled as questions so I am adding the correct labels instead

:pencil2: Tone and grammar improvements to templates

---

.github/workflows/release.yaml

Follows #636  and adds the missing permissions for publishing 🤦🏽‍♀️

:bug: Add missing permissions for publishing

---

docusaurus-docs/conda-store-ui/explanations/ui-elements.md
docusaurus-docs/conda-store-ui/how-tos/index.md
docusaurus-docs/conda-store-ui/how-tos/request-packages.md
docusaurus-docs/conda-store-ui/references/release.md
docusaurus-docs/conda-store-ui/tutorials/index.md
docusaurus-docs/conda-store/explanations/conda-concepts.md
docusaurus-docs/conda-store/explanations/conda-store-concepts.md
docusaurus-docs/conda-store/references/release.md
docusaurus-docs/jupyterlab-conda-store/release.md
docusaurus-docs/src/css/custom.css

N/A
- Removes changelog files
- Removes border around conda-store logo
- Updates "in development" notes, sidebar position, etc. for some files

Misc clean-up docs structure

---

docusaurus-docs/docusaurus.config.js

Fixes #408
- Adds plausible tracking snippet as script, ref: https://plausible.io/docs/docusaurus-integration

Add plausible tracking snippet

---

docusaurus-docs/community/policies/upstream-contribution.md

Adresses #399 
Closes #679
This pull request adds a minimal upstream contribution policy.

Add upstream contribution policy

---

.github/PULL_REQUEST_TEMPLATE.md

No Issue
- adds a How to Test section to the PR template
This is the test. It seems to work  :D

add how to test section to PR template

---

CHANGELOG.md

Address #755 
- Updates changelog entries based on [auto-generated release notes](https://github.com/conda-incubator/conda-store/releases/tag/2024.3.1).

Add CHANGELOG entries for v2024.3.1

---

.github/workflows/build_docker_image.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml

Split from #792 
Bumps GH actions versions to more up-to-date ones

MAINT -  Bump actions versions

---

CHANGELOG.md
conda-store-server/conda_store_server/__init__.py
conda-store-server/hatch_build.py
conda-store/conda_store/__init__.py
docusaurus-docs/static/openapi.json

Closes #876.
This PR releases `2024.9.1`.

REL - 2024.9.1

---

CHANGELOG.md
conda-store-server/conda_store_server/__init__.py
conda-store/conda_store/__init__.py
docusaurus-docs/static/openapi.json

This reverts commit f46e0c3e80c20149cc8808527f14675d44510fea.
The latest release had a failing workflow. This PR reverts the commit which updates the version strings and the changelog in preparation for another release attempt.

Revert "REL - 2024.9.1 (#880)"

---

docusaurus-docs/community/introduction.md
docusaurus-docs/community/roadmap.md

This PR adds a `ROADMAP.md`. It's currently a preliminary 2024 roadmap, but we can reuse this in later years as well.

[MAINT] Add the 2024/2025 roadmap

---

CHANGELOG.md
conda-store-server/conda_store_server/__init__.py
conda-store-server/hatch_build.py
conda-store/conda_store/__init__.py

REL - 2024.10.1

---

.github/ISSUE_TEMPLATE/config.yml

Fixes # 920
This pull request fixes link to docs in issue tempates

Update docs link

---

conda-store-server/conda_store_server/__init__.py
conda-store/conda_store/__init__.py

ref: https://github.com/conda-incubator/conda-store/issues/967

Bump dev version

---

conda-store-server/Dockerfile
conda-store/Dockerfile

Bumping our base image to the latest release

MAINT - Bump base Docker image version

---

.dependabot.yml

While going through issues and PRs, I noticed that Dependabot was not respecting our labels configuration/schema, so I am pushing a quick update to the config.

MAINT - Update dependabot configuration

---

CHANGELOG.md
conda-store-server/conda_store_server/__init__.py
conda-store-server/hatch_build.py
conda-store/conda_store/__init__.py

REL - 2024.11.2

---

conda-store-server/conda_store_server/_internal/server/templates/user.html
docusaurus-docs/conda-store/references/configuration-options.md
docusaurus-docs/conda-store/references/database.md

Fixes a typo (bellow to below)

fix below typo (bellow -> below)

---

tools/cut-release-pr.sh

Consolidating project scripts into the `tools` directory. To run the cut release script, ensure you run from the root of the project.  For example:
```
$ ./tools/cut-release-pr.sh -r release_version -c conda_store_ui_version\n"
```

Move cut-release-pr script into tool dir

---

conda-store-server/conda_store_server/_internal/orm.py
conda-store-server/conda_store_server/_internal/schema.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/utils.py
conda-store-server/conda_store_server/_internal/worker/build.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/exception.py
conda-store-server/tests/test_api.py

This PR does a little bit of refactoring to consolidate all the `Exception` related classes into one exception module in `conda_store_server.exception`. This is to increase legibility of the code.

Consolidate exception classes :broom: 

---

.github/workflows/build_docker_image.yaml
.github/workflows/release.yaml

ref: https://docs.docker.com/build/ci/github-actions/multi-platform/

Build and push docker images for multiple platforms in one step

---

CHANGELOG.md
conda-store-server/conda_store_server/__init__.py
conda-store/conda_store/__init__.py

Closes https://github.com/conda-incubator/conda-store/issues/1072

REL - 2025.2.1
