conda-store-server/Dockerfile
docker-compose.yaml
docs/development.md

The proposed changes are needed in an Apple Silicon MBP to emulate `amd64` archs for `conda-store-server`, due to the `fakechroot` dependency.
I have also put a [PR](https://github.com/conda-forge/fakechroot-feedstock/pull/3) to build `fakechroot` on `aarch64` (and `ppc64le`), which might allow us to avoid the emulation, but for now this is needed.

Support running `docker-compose` from archs != amd64

---

conda-store-server/Dockerfile
conda-store/Dockerfile

Change base Docker image for `micromamba`, a lightweight `conda` drop-in replacement with faster solving times.

Use micromamba

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/conda.py
docker-compose.macos.yaml

Instead of downloading the raw `repodata.json`, get the bz2-compressed version, which we can decompress in memory.
Some profiling shows a significant speed-up with my not-so-stable connection.
`repodata.json`
```python
%%timeit
url = "https://conda.anaconda.org/conda-forge/linux-64/repodata.json"
resp = requests.get(url)
resp.raise_for_status()
data = resp.json()
```
`repodata.json.bz2`
```python
%%timeit
url = "https://conda.anaconda.org/conda-forge/linux-64/repodata.json.bz2"
resp = requests.get(url)
resp.raise_for_status()
data = json.loads(bz2.decompress(resp.content))
```
Note this branch stemmed out of #74

Download compressed repodata.json

---

conda-store-server/conda_store_server/build.py
docker-compose.macos.yaml

Given the issues stated in #73, I am providing this workaround for now. It disables volumes and Docker image creation by setting an env var.
MacOS hosts need to run `docker-compose -f docker-compose.macos.yaml up --build` to deploy.

provide a docker-compose.yaml file for macos

---

conda-store-server/Dockerfile
conda-store-server/conda_store_server/build.py
docker-compose.macos.yaml

This PR adds support to create envs with Mamba instead of conda (if available).
* The base docker image is now `mambaforge` instead of `micromamba` (we end up downloading a full mamba install anyway due to dependencies)
* It will use mamba to create the envs if it's found in PATH. If not, fallback to `conda` and cross your fingers.
* Peak memory didn't go beyond 750MB for a simple env (1.5GB for normal conda, I recall?)
* Time taken: `conda` takes 3:30 min for a python+flask env. `mamba` did it in 55s.

Use mamba if available; fallback to conda

---

conda-store-server/Dockerfile
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/setup.py
conda-store/Dockerfile

There were some instances of hardcoded `linux-64` strings as the default platform, which assumed that the server components were running on `linux/amd64` architectures. This is not necessarily true (e.g. MacOS M1 will report `aarch64`), so instead we use the Conda API to obtain the conda-style platform code.

use conda api to obtain host platform

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/storage.py
docker-compose.yaml

Add support for external url for s3 using minio

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/__init__.py
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/views/__init__.py
conda-store-server/conda_store_server/server/views/metrics.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/environment-dev.yaml
conda-store-server/setup.py
shell.nix

This endpoint will serve several purposes:
- easy integration with prometheus
- provide an easy way to query the health of the cluster from ci

Adding prometheus metrics endpoint

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/worker/tasks.py

Closes #12. This for the most part copies #85 but adds support for the celery backend.

Adding conda env export

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/worker/tasks.py

Users can now select old builds for a given environment. Notice the checkmarks. I'm sure a better icon could be used.

Enabling rollbacks of environment builds

---

conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/navigation.html
conda-store-server/conda_store_server/server/templates/user.html
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/environment.yaml
docs/development.md
tests/assets/conda_store_config.py
tests/assets/jupyterhub_config.py

Add more authentication methods

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/app.py

Such a small PR but was the source of a lot of flask webpage / database state issues. The problem was that the session object in sqlalchemy was being reused between requests (not transactions) and this was causing the web api/ui to not reflect the true state of the database once the worker deleted/updated some environments.

Adding scoped sqlalchemy sessions

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/utils.py
conda-store-server/conda_store_server/worker/tasks.py

Before this PR is a user decided to rollback an environment it would trigger a task (to be run at an unknown time in the future) that will update the database and then adjust the symlink pointing to the current environment. Now the database is updated with the request and the task now consults the database on what is the correct build to symlink to (making the task idempotent).

Make conda-store environment build update command syncronous

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/storage.py
conda-store-server/conda_store_server/worker/tasks.py

Currently the delete button trigger a task to delete the given build. The major problem with this is that when the user clicks delete the environment is not deleted immediately (this isn't possible so we have to mark the build for deletion). Then a task is kicked off to delete the given build. A conda_store configuration setting is available for users to choose which build artifacts are deleted.

Adding syncronous delete method for environment builds

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/worker/app.py
conda-store-server/conda_store_server/worker/tasks.py

This sure makes the logs of conda-store a bit messier but at the same time enables much faster builds.

Parallel artifact builds

---

docs/administration.md

Additionally have an FAQ section of an error log when celery crashes
due to an out of memory error (OOM).

Adding docs about resources requirements for conda-store

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/worker/tasks.py

Closes #124
Adding the ability to entirely delete an environment

Adding logic to delete environments to rest api and ui

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py

In the `conda_store_server.api` methods for list_environment, list_builds, and list_namespaces there is now a `show_soft_deleted` option which is by default False.
We set show_soft_deleted to True for builds since often we would like to see builds that have been deleted but several artifacsts are still kept. 
Closes #191

Fix 191 to only show non-deleted environments/namespaces

---

conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/templates/home.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py
docs/contributing.md

This PR addresses #203 by adding a new API endpoint at `/api/v1/build/<build_id>/yaml/` which exports the given build as a YAML-formatted environment file.
* Added route for exporting builds as YAML files
* Modify documentation to describe usage
* Inside `docs/contributing.md` there were some empty lines with only whitespace in them, and some lines with trailing whitespace. These got removed automatically by my editor. If these changes are just noise, I can remove them.
* Modified `home.html` and `build.html` templates to use the new endpoint
* Removed the old endpoint

Add API endpoint for exporting YAML environment files

---

conda-store/environment.yaml

Yesterday the following command from https://github.com/Quansight/gator/tree/conda-store-integration failed for me:
```sh
cd conda-store/examples/docker/
docker compose up --build
```
I traced back the errors until I was able to reproduce the same error locally when trying to pip install [Quansight/gator[branch=list-installed-conda-store-packages]](https://github.com/Quansight/gator/tree/list-installed-conda-store-packages)
As you can see in [my terminal log](https://gist.github.com/gabalafou/0ca8e806afa7996ee2fd466441a09a09), trying to pip install that repo branch when `node --version` = 17 fails, whereas it succeeds when `node --version` = 16.

Pin nodejs to v16 in conda-store/environment.yaml

---

conda-store-server/conda_store_server/server/app.py

Closes #217
This is a painful issue when dealing with https. In https the redirect
was causing CORS issues when redirecting the user from /api/v1 ->
/api/v1/ for example. This will no longer be an issue with this fix.

Accepting paths with and without a trailing slash

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/views/api.py

Closes #227 
This PR adds further validation on the name and namespace used in Conda-Store. Additionally allows for namespaces and names to support email like namespaces/names.

Adding an validation for namespace and name via regex

---

.github/workflows/documentation.yaml
.github/workflows/tests.yaml
conda-store-server/conda_store_server/server/app.py
docs/administration.md
tests/vale/styles/vocab.txt

This uses Flask ProxyFix https://werkzeug.palletsprojects.com/en/2.0.x/middleware/proxy_fix/ with setting `c.CondaStoreServer.behind_proxy = True|False`
This will address the issue seen in quansight/qhub#1121

Adding ability for conda-store server to use proxy X-Forward- headers

---

examples/docker/assets/conda_store_config.py

I think this got overlooked in #250

Add concurrency setting to example Docker Conda Store config file

---

conda-store-server/Dockerfile
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/conda.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/worker/tasks.py
docs/administration.md
tests/assets/conda_store_config.py

In PR #252 a function was added to allow for arbitrary modification and validation of the specification. This PR aims to enhance this feature with additional settings to allow for easy validation/modifications of specifications.
Via:
- `CondaStore.conda_default_channels`
- `CondaStore.conda_allowed_channels`
- `CondaStore.conda_default_packages`
- `CondaStore.conda_required_packages`
- `CondaStore.conda_included_packages`
Additionally `conda_allowed_channels` is now enforced and packages cannot be fetched from channels not in this list.
Closes #253

Specification custom validation and modifications

---

conda-store-server/conda_store_server/server/templates/base.html
conda-store-server/conda_store_server/server/templates/create.html
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py

Closes #260
We are now dependant on the rest api

Error messages on api requests printed to users

---

.gitignore
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/views/api.py
docs/contributing.md

Here is the work to have an exact search in the api for the two packages endpoints : `/api/v1/package` and `/api/v1/build/<build-id>/packages/`.
As explained in the issue #263, I chose to use an `exact` parameter, complementary to `search`, instead of the alternative design (have `search` and `name` parameters, which would imply to choose arbitrarily between one of the two when both parameters are given)
I tested it manually with an env containing `pandas` and `pandas_schema` and querying the API accordingly.
The only solution I found with sqlalchemy to achieve exact match is to use the `like` operator, forcing me to replace occurences of `%`.

Fix #263 : exact search

---

conda-store-server/conda_store_server/environment.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/views/api.py

Fix #294 : Yaml spec file uses pip options.
Tests : 
- First, I've tried a public pypi mirror : 
```yaml
channels:
- conda-forge
dependencies:
- python=3.6
- pandas
- ipykernel
- pip
- pip:
- --index-url https://mirrors.sustech.edu.cn/pypi/simple
- flask
name: test_env_3
prefix: null
```
Setting up a pypi mirror is cumbersome. either I use bandersnatch but it requires 250GB (which I haven't), or [this repo](https://github.com/montag451/pypi-mirror) but it doesn't provide wheels. So for the sake of progressing faster, I've used a public mirror. 
This yaml works and builds.
```yaml
channels:
- conda-forge
dependencies:
- python=3.6
- pandas
- ipykernel
- pip
- pip:
- --index-url https://mirrors.sustech.edu.cn/pypi/simple
- --test quansight
- flask
name: test_env_3
prefix: null
``` 
This one …

Fix #294 : yaml spec file uses pip options

---

conda-store-server/conda_store_server/environment.py

Weird thing, I swear I had seen an error about `'dict' object has no attribute 'extend'` before, indicating that the pip dependencies was a dict, but....
Actually it looks like the pip dependencies will be a `schema.CondaSpecificationPip`, not a dict.
This fixes an issue we were seeing when using `c.CondaStore.pypi_included_packages`:
- If a `pip:` section existed in the original yaml, a second `pip:` section would be
added with the 'included' packages rather than appening to the original `pip:` section.
For example, creating an environment with this yaml:
```
dependencies:
- pip:
- requests
```
And this config:
```
c.CondaStore.pypi_included_packages = ["pandas"]
```
Would result in this:
```
dependencies:
- pip:
- requests
- pip:
- pandas
```

More pip fixes

---

examples/docker/docker-compose.yaml

This PR adds back in a `POSTGRES_USER` environment variable into `examples/docker/docker-compose.yaml` to ensure that a `postgres` user is created when the docker image is run. Without this change the docker container fails to run. Resolves #318.
I've tested this manually to make sure it works, but would appreciate feedback.

Add `POSTGRES_USER` env var back into docker example

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py

Closes #323
Additionally:
- search in environment now considers the namespace
- name is an additional allowed query parameter
- search query parameter is allowed in `/` home

Added namespace query parameter to /api/v1/environment/?namespace=<namespace>

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/server/views/api.py

Adds the ability to filter builds and environments on:
- packages in the environment
- status of the build
- artfacts that exist for given build
This is critical for nb_conda_store_kernels being able to efficiently filter out given environments that are ready to run. Additionally qhub needs this for dask_gateway and cdsdashboards extensions.

API builds/environments filter on packages, status

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/environment.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/tests/test_auth.py
conda-store/conda_store/api.py
conda-store/conda_store/cli.py
flake.nix

This is a necessary feature for integrating Conda-Store into CDSDashboards and Dask-Gateway. I need some way of provisioning tokens with smaller credentials.
Closes #331

Adding token endpoint along with tests

---

conda-store-server/conda_store_server/server/views/api.py

Fixes #351 : allows sorting builds by `started_on`, `scheduled_on` or `ended_on`

fix 351 : sort builds by start/scheduled/end dt

---

conda-store-server/conda_store_server/server/app.py

This fix is necessary for the UI to access the API.
Without this fix, the API returns `403` whatever we do.

Fix CORSMiddleware to accept headers

---

conda-store-server/conda_store_server/app.py

I noticed a bug when updating an env from the UI, i.e. using the `POST /conda-store/api/v1/specification/` endpoint. 
I plead guilty :)

Fix when updating an env

---

conda-store-server/conda_store_server/server/app.py

CORS appeared again, this time using the `login` endpoint. It appears we need to let the CORSMiddleware be flexible on the methods it accepts.

Fix CORS on login endpoint

---

conda-store-server/conda_store_server/schema.py

I realize I forgot to return the env description in GET api/v1/environment/{namespace}/{environment_name}

return description in get api/v1/environment/

---

conda-store-server/conda_store_server/schema.py

I forgot to put the description of env as optional in the ORM schema, leading to validation errors when requesting the API.
This fix is important for the UI to work.

env description is optional

---

conda-store-server/conda_store_server/server/app.py

closes #395 
This is a very simple fix to make sure we can still run `uvicorn` without pinning it in main. We should rethink the debug mode strategy for the main app if there is a need for it... or pin uvicorn to '<0.19.0'

Removing unsupported `--debug` flag from `uvicorn.run`

---

docs/index.rst

Fix "~Goveranance~" ➞ "Governance"

Fix typo in docs

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
docs/administration.md

This PR fixes issue #439 
The default indexed channels are `main` and `conda-forge`.
The issue suggested the name `conda_indexed_channels`. For clarity, I'd suggest to rename it as `conda_prefetched_channels` or something similar. 
The name `conda_indexed_channels` confused me at first, because "indexed channels" means to me "channels already indexed", and not "channels to index".

Fix #439 : conda indexed channels

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/user.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/worker/tasks.py
docs/administration.md
tests/test_api.py

Closes #440 
This ties into the current methods for conda-store validation. We have:
- authentication/authorization (is the given entity capable of performing action on given resource)
- validate specification which validates that the given specification complies with conda-store rules
We are adding a new validate action which at the namespace level checks if the given action is permissible. This is because validation needs to happen additionally outside of the "entity" level. Conda-Store can itself trigger new builds when watching the filesystem.

Function for system validation of conda-store actions

---

conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml

Pinning SQLAlchemy to avoid solving with incompatible version >= 2

Pin SQLAlchemy <=1 .4.47

---

conda-store-server/conda_store_server/alembic/versions/16f65805dc8f_split_conda_package_into_conda_package_.py

Fix #476 : Delete dangling build artifacts before migration.

Fix #476 : delete dangling build artifacts before migration

---

conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/testing.py
conda-store-server/tests/conftest.py
conda-store-server/tests/test_server.py
conda-store-server/tests/test_testing.py

Making it such that conda-store-server can run what used to be the integration tests.

Adding tests for fastapi server without need for integration

---

conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/tests/test_server.py

Currently there is a way to get this information in the UI but wanted a way to get these usage statistics via the api for clients.

Adding an api method for getting usage data for namespaces

---

.pre-commit-config.yaml
conda-store-server/conda_store_server/server/app.py
conda-store-server/pyproject.toml
conda-store/pyproject.toml

Resolves #475. Pre-commit runs each hook in its own isolated environment so the dependencies aren't required in the dev deps section.

add pre-commit

---

conda-store-server/conda_store_server/alembic/versions/b387747ca9b7_role_mapping.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml
conda-store-server/pyproject.toml
conda-store-server/tests/test_auth.py
conda-store-server/tests/test_db_api.py
docs/contributing.md

This PR aims at solving issue #491

Role mapping

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/schema.py

Better docs and error messages around pip packages

---

conda-store-server/tests/conftest.py

See https://github.com/Quansight/conda-store/actions/runs/5613636006/job/15210071085 for examples

Change the tests when using sqlite to not check threads (celery + traitlets + fastapi) are doing weird things

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/tests/test_server.py
tests/test_api.py

This PR adds a new API endpoint to update a namespace's role mappings and metadata.
the `PUT /conda-store/api/v1/namespace/{namespace}/` endpoint takes a JSON payload to update the metadata, the role mappings, or both.
- update the metadata : 
```json
{
"metadata": {"my_key":"my_value"}
}
``` 
- update the role mappings : 
```json
{
"role_mappings": {
"admin/admin": ["admin", "viewer", "developer"],
"admin/*": ["viewer"],
"demo/*": ["developer"]
}
}
```
- update both :
```json
{
"metadata": {"my_key":"my_value"},
"role_mappings": {
"admin/admin": ["admin"],
"admin/*": ["viewer"],
"demo/*": ["developer"]
}
}
```
@costrouc tell me if that works for you or if you'd see another approach or pattern.
According to the original issue #491 : 
> - namespace update rest api method that uses the …

API : update a namespace's metadata and role mappings

---

conda-store-server/conda_store_server/server/auth.py
docs/administration.md

This allow the setting of a cookie for `Authentication.cookie_domain = "example.com"`. This allows the cookie to be valid for `example.com` along with `*.example.com`

Allow setting a subdomain cookie for conda-store

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/registry.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/dependencies.py
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/server/views/conda_store_ui.py
conda-store-server/conda_store_server/server/views/metrics.py
conda-store-server/conda_store_server/server/views/ui.py
conda-store-server/conda_store_server/testing.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml
conda-store-server/tests/conftest.py
conda-store-server/tests/test_actions.py
conda-store-server/tests/test_app_api.py
conda-store-server/tests/test_auth.py
conda-store-server/tests/test_db_api.py
conda-store-server/tests/test_testing.py
conda-store-server/tests/test_traitlets.py

Closes https://github.com/conda-incubator/conda-store/issues/520

Proper handling of sqlalchemy database sessions in fastapi and celery

---

conda-store-server/environment-dev.yaml
conda-store-server/environment.yaml

It is also an implicit dependency of conda-docker, but conda-docker may become an optional dependency for Mac (#507).

Add python-docker as an explicit dependency in environment.yml

---

README.md
SECURITY.md
conda-store-server/conda_store_server/alembic/versions/16f65805dc8f_split_conda_package_into_conda_package_.py
conda-store-server/pyproject.toml
conda-store/pyproject.toml
docs/conf.py
docs/contributing.md
docs/installation.md

This PR is part of https://github.com/conda-incubator/conda-store/issues/514
This PR,

Update repository URL

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/views/api.py
tests/assets/conda_store_config.py
tests/conftest.py
tests/test_api.py
tests/test_metrics.py
tests/test_playwright.py

Most routes are added as shorthands additionally conda-lock.yaml/yml added for conda-lock compatibility.
Closes issue https://github.com/conda-incubator/conda-store/issues/517

Adding additional routes for conda-lock lockfile

---

conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/worker/tasks.py
docs/administration.md

Celery broker support varies for inspecting active tasks. The redis backend has great support for this feature. If you use the sqlalchemy backend it will not support inspecting active tasks.
Closes https://github.com/conda-incubator/conda-store/issues/170
Closes https://github.com/conda-incubator/conda-store/issues/171

Adding support for cleaning up builds stuck in BUILDING state

---

.readthedocs.yaml
docs/environment-docs.yml

Addresses #532 (hence, #514)
Read The Docs build have been failing due to conda solve errors: https://readthedocs.org/projects/conda-store/builds/
Currently, we use [conda-store-server/environment-dev](https://github.com/conda-incubator/conda-store/blob/main/conda-store-server/environment-dev.yaml) for the docs build. We only need a subset of libraries for the docs, so adding a simpler YAML in this PR to get the docs building successfully.
Note that this is an intermediate fix to have functioning documentation. The plan is to overhaul the docs and move to Docusaurus - #397

🔧 Create new docs env

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/general-issue.yml
.github/PULL_REQUEST_TEMPLATE.md

This PR is part of https://github.com/conda-incubator/conda-store/issues/514
This PR,

Update issue and pull request templates

---

conda-store-server/conda_store_server/utils.py

Fixes the issue described at
https://github.com/conda-incubator/conda-store/issues/507#issuecomment-1679678805
I don't know yet what should be done on Windows. Windows support will need to be investigated separately. It will likely be a lot more work than macOS support.
Fixes # .
- a
- b
- c

Make the disk_usage() function work on macOS

---

conda-store-server/conda_store_server/action/generate_conda_docker.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/schema.py

conda-docker doesn't work on Mac, and making it work is not straightforward, so for now we just disable it when we aren't on Linux.
With this and #537, basic Mac support seems to work with --standalone (#507). I'm not sure what else I should be testing, but I can create environments and they appear to be functional.

Don't run conda-docker on Mac

---

conda-store-server/conda_store_server/server/auth.py

Fixes #512
Deletes cookies properly on logout. Code has been formatted with Black. 
- a
- b
- c

Delete subdomain keys on logout

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/schema.py

Allow all channels by default

---

conda-store-server/conda_store_server/worker/app.py
conda-store-server/tests/conftest.py

Fixes #538.
- Prevents traitlets from picking `sys.argv`
- Fixes pytest issues
With this addition now you can call pytest flags in whatever order you want,
```
pytest tests/test_app_api.py -x -v
```

Prevent traitlets from picking sys.argv during tests

---

conda-store-server/conda_store_server/worker/tasks.py

Update build metadata on deletion, fix misc bugs

---

tests/conftest.py
tests/test_playwright.py

Related to https://github.com/conda-incubator/conda-store/issues/570 
I have to use a non-default port (not 5000) on my mac for development. This PR allows the playwright tests to run on any port instead of hard-coding the port. 
- allows the playwright tests to run on a configurable port via env var
- creates a pytest fixture for the port
- updates the playwright test to use the new fixture

Make conda-store-server test port configurable

---

conda-store-server/pyproject.toml

Fixes #578 .
Note, we will also need to make sure to fix this in the conda-forge feedstock.
- a
- b
- c

Make conda-docker a dependency in Linux only in pyproject.toml

---

.github/workflows/build_docker_image.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
conda-store-server/Dockerfile
conda-store/Dockerfile
docker-compose.yaml
examples/docker-without-nfs/docker-compose.yaml
examples/docker/docker-compose.yaml

Fixes #614
Part of #599 
updates Dockerfile for conda-store to have a prod target that does not install pip dependencies in editable mode, and a dev target that does.
- Update Dockerfile as described above
- Set github actions to use prod targets

update conda store dockerfile to have prod target

---

.github/workflows/tests.yaml
conda-store-server/environment-dev.yaml
conda-store-server/environment-macos-dev.yaml
conda-store-server/environment.yaml

Fixes #632 
Fixes #630 
- This should fix the flaky CI errors - it ensures we do not mix defaults and conda-forge, so we use miniforge to set all the environments.
- Added some quick fixes to the env files to silence the pip-related warnings and ensure defaults are not used (I changed the `microsoft` channel capitalisation, and that might fix #630, though I could not reproduce locally 🤷🏽‍♀️  so I am not sure that is the root cause)

ENH  -  Use miniforge throughout

---

conda-store-server/pyproject.toml

Fixes #627 
This should fix the python-docker import issue on non-Linux OSs

:heavy_plus_sign: Add python-docker

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/action/base.py
conda-store-server/conda_store_server/action/generate_conda_export.py
conda-store-server/conda_store_server/action/install_lockfile.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/dbutil.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/storage.py
conda-store-server/conda_store_server/utils.py
conda-store-server/conda_store_server/worker/app.py
conda-store-server/environment-windows-dev.yaml
conda-store-server/hatch_build.py
conda-store-server/tests/test_actions.py
conda-store-server/tests/test_usage.py
docs/administration.md
docs/contributing.md
docs/user_guide.md

Windows support

---

conda-store-server/conda_store_server/__init__.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/storage.py
conda-store-server/tests/conftest.py

This work is part of #513. Original PR: #554.

Store the state and database files in ~/.conda-store by default

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/client.py
conda-store-server/conda_store_server/server/app.py
conda-store/conda_store/cli.py
conda-store/tests/authenticated-tests.sh
conda-store/tests/authenticated-token-tests.sh
conda-store/tests/unauthenticated-tests.sh
docker-compose.yaml
docs/administration.md
docs/contributing.md
docs/installation.md
docs/user_guide.md
examples/docker-without-nfs/assets/conda_store_config.py
examples/docker-without-nfs/docker-compose.yaml
examples/docker/assets/conda_store_config.py
examples/docker/docker-compose.yaml
examples/kubernetes/conda-store-server.yaml
examples/kubernetes/conda-store-worker.yaml
examples/kubernetes/files/conda_store_config.py
examples/standalone/docker-compose.yaml
examples/ubuntu2004/templates/conda_store_config.py.j2
tests/assets/conda_store_config.py
tests/conftest.py

Fixes #618  .
Replaces port 5000 with port 8080 as the default port to run on. Port 8080 is not a privileged port, but is an alternate port for HTTP. Port 5000 is in use on some Mac computers which causes conflicts.
- Replaces port 5000 with port 8080 as default port.

replace port 5000 with port 8080

---

conda-store-server/conda_store_server/alembic/versions/d78e9889566a_add_status_info.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/utils.py
conda-store-server/tests/test_db_api.py
conda-store-server/tests/test_server.py
docs/administration.md
tests/test_api.py

Check the size of `build_path`

---

conda-store-server/conda_store_server/action/generate_conda_docker.py
conda-store-server/conda_store_server/build.py
conda-store-server/tests/test_actions.py

Disable code that depends on conda-docker

---

docs/contributing.md
docusaurus-docs/community/contribute/contribute-code.md
docusaurus-docs/community/contribute/contribute-docs.md
docusaurus-docs/community/contribute/issues.md
docusaurus-docs/community/contribute/testing.md
docusaurus-docs/community/maintenance/github-conventions.md
docusaurus-docs/community/maintenance/release.md
docusaurus-docs/community/maintenance/reviewer-guidelines.md
docusaurus-docs/community/maintenance/triage.md
docusaurus-docs/conda-store/introduction.md

This removes broken references to the changelog in the docs

BUG - Remove links to changelog

---

conda-store-server/environment-dev.yaml
conda-store-server/environment-macos-dev.yaml
conda-store-server/environment-windows-dev.yaml

A new version of docker-py was released and it now causes issues with docker-compose because the latter doesn't work with the new version. This PR adds a bound to make sure the versions are compatible.
New version that causes problems:
```
docker-py                             7.0.0  pyhd8ed1ab_0        conda-forge/noarch
```
Old version that works:
```
docker-py                             6.1.3  pyhd8ed1ab_0        conda-forge/noarch
```
This error was printed on CI during Tests / integration-test conda-store-server (pull_request):
```
Traceback (most recent call last):
File "/usr/share/miniconda3/envs/test/bin/docker-compose", line 11, in <module>
sys.exit(main())
File "/usr/share/miniconda3/envs/test/lib/python3.10/site-packages/compose/cli/main.py", line 81, in main
command_func() …
```

Place a bound on docker-py

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/templates/base.html
conda-store-server/conda_store_server/server/templates/environment.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/tests/test_server.py
tests/test_api.py

Closes https://github.com/conda-incubator/conda-store/issues/306
Build canceling exposed at `PUT /api/v1/build/<build-id>/cancel/` and added a new permissions `build::cancel` which is available by default for `admin` and `developer` roles.

Adding build canceling (only works with compatible celery brokers redis and rabbitmq)

---

conda-store-server/conda_store_server/action/generate_lockfile.py
conda-store-server/tests/test_actions.py

This PR sets the channel priority to strict to avoid issues during solves when  multiple channels that were not specified are being used. This is done by passing the command line option `--strict-channel-priority` via the environment variable `CONDA_FLAGS`, which is used by conda-lock, which is a library conda-store uses to solve dependencies.
`CONDA_FLAGS` is used because it's a method of passing options that's local to conda-lock as opposed to editing global conda configuration files. Editing user configuration files may lead to unexpected issues in contexts where conda-store is used in standalone mode. Those configuration files affect how conda works outside of conda-store, which might be important to end users.
From the documentation at …

Set channel priority to strict, print config info

---

conda-store-server/conda_store_server/conda_utils.py
conda-store-server/tests/test_actions.py

Fixes #602.
This pull request: appends the trailing slash to `normalized_channel_url` via string interpolation. The previous method of using the `/` operator was ignoring the trailing slash on Windows, which caused a `channel_replacements` lookup failure.
On Linux:
```
In [2]: yarl.URL("foo") / "./"
Out[2]: URL('foo/')
```
On Windows the slash is not appended, so the lookup in `channel_replacements` failed:
```
In [4]: yarl.URL("foo") / "./"
Out[4]: URL('foo')
```

Use string substitution in `normalized_channel_url`

---

conda-store-server/conda_store_server/worker/tasks.py

Fixes #707.
This pull request: installs a signal handler that terminates worker tasks on Ctrl-C (SIGINT).
If the requested signal isn't supported on the current platform, the operation will be ignored.
Notes:
- we cannot use celery control because it's broker-dependent, which wouldn't work with standalone
- printing a worker pid and asking users to terminate that wouldn't work because celery beat would respawn
- using `install_worker_term_hard_handler` wouldn't work because not all tasks would be terminated
- using a signal handler is the only solution I've found given the above constraints, it's what `install_worker_term_hard_handler` uses internally as well.
Tested on Windows and Linux. All processes are terminated as expected.

Terminate worker tasks on SIGINT

---

conda-store-server/conda_store_server/server/app.py

Fixes #562.
- logs address and port on startup
- shows exception trace from `uvicorn.run`.
Example output when the port is already in use:
```
INFO  [app] Starting server on 0.0.0.0:8080
Traceback (most recent call last):
File "/home/test/miniconda3/envs/conda-store-server-dev/lib/python3.10/site-packages/uvicorn/server.py", line 160, in startup
server = await loop.create_server(
File "/home/test/miniconda3/envs/conda-store-server-dev/lib/python3.10/asyncio/base_events.py", line 1493, in create_server
raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```

Log address and port, show exception trace from `uvicorn.run`

---

conda-store-server/conda_store_server/action/generate_lockfile.py

Fixes #719.
This pull request makes it possible to set the CUDA version by passing the value of the `CONDA_OVERRIDE_CUDA` specification variable to the `with_cuda` parameter of conda-lock.
See https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages
How I tested this:
- Created this test env _via the server admin environment page_ because _conda-store UI strips variables even in raw YAML mode_, so it doesn't work there:
```yaml
channels:
- conda-forge
dependencies:
- pytorch
- ipykernel
- pip:
- nothing
description: test2
name: test3
prefix: null
variables:
CONDA_OVERRIDE_CUDA: '12.0'
```
- Checked that the pytorch package in the generated lockfile has constraints matching this version of cuda. The url of the pytorch package should …

Pass `CONDA_OVERRIDE_CUDA` to `with_cuda` of conda-lock

---

conda-store-server/conda_store_server/alembic/versions/0f7e23ff24ee_add_worker.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/app.py
conda-store-server/conda_store_server/worker/tasks.py

Fixes #605.
conda-store can run via docker and in standalone mode:
- in standalone mode, the `--standalone` CLI parameter must be used to start the worker sub-process
- when running via docker, this CLI parameter is not used because a dedicated worker process is started by docker-compose.
However, there might be cases where users forget to pass the `--standalone` parameter when running in standalone mode. This is a problem because the server cannot execute any tasks without the worker, so it must be running.
This PR adds a check that verifies whether the worker is running and prints an error message if not.
The worker is configured via a number of parameters, like `celery_broker_url`, which can either point to a database connection or use Redis:
```py
@default("celery_broker_url")
def …
```

Check if worker is initialized

---

.github/workflows/tests.yaml
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/orm.py
conda-store-server/tests/test_server.py
docusaurus-docs/conda-store/references/faq.md

Fixes #588.
- adds support for the Windows [extended-length prefix](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) (`"\\?\"`) via the `win_extended_length_prefix` option
- adds a test
- updates the docs.

Add extended-length prefix support

---

conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/orm.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/tests/test_auth.py
conda-store-server/tests/test_db_api.py
docusaurus-docs/conda-store/references/auth.md
docusaurus-docs/conda-store/references/configuration-options.md
tests/test_api.py

Fixes #675.
- adds the alias `editor` for `developer` to role mappings, which is supported by the HTTP API and the DB
- adds tests
- updates documentation.
The auth flow is as follows:
- an HTTP API is called to set the role (can be either `editor` or `developer`)
- the role is written to the DB (always written as `developer`)
- when some page is accessed, the role is checked on auth by matching the DB value against `role_mappings`
- `developer` from the DB is matched against `editor` or `developer` in `role_mappings` (in this order).
All user-visible parameters (the HTTP API and the `role_mappings` setting) allow for both `editor` and `developer`.
The name `editor` is preferred, which is reflected in the documentation.
The name `developer` is supported for …

Add support for the `editor` role

---

.pre-commit-config.yaml
conda-store-server/tests/conftest.py
conda-store-server/tests/test_actions.py
conda-store-server/tests/test_auth.py
conda-store-server/tests/test_db_api.py
conda-store-server/tests/test_server.py
conda-store-server/tests/test_usage.py
conda-store-server/tests/user_journeys/utils/api_utils.py
conda-store-server/tests/user_journeys/utils/time_utils.py
tests/conftest.py
tests/test_api.py
tests/test_playwright.py

Fixes #768.
This pull request changes the linter config to run on tests and docs.

Run linter on tests and docs

---

conda-store-server/conda_store_server/alembic/versions/03c839888c82_add_canceled_status.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/schema.py
conda-store-server/conda_store_server/server/templates/build.html
conda-store-server/conda_store_server/server/views/api.py
conda-store-server/conda_store_server/worker/tasks.py
conda-store-server/tests/user_journeys/utils/api_utils.py
tests/test_api.py

Fixes #547.
This pull request: adds status `CANCELED`, which is displayed in the web UI when the user cancels a build.
- Run via docker
- Cancel a build via the admin UI by clicking on the cancel button
- The status of the build should say "CANCELED".

Add status `CANCELED`

---

conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

Fixed https://github.com/conda-incubator/conda-store/issues/669.
This PR implements an integration test which checks that an admin can create an environment in a shared namespace and delete both the environment and the namespace.
- Adds an integration test which logs a user in and deletes an environment in a shared namespace and the namespace itself
- Modifies the existing `test_admin_user_can_create_environment` test; previously, that test was doing something very similar to what the new test implemented in this PR does. With this change, the existing test now tests that an admin can create an environment in the `default` namespace, more closely matching the existing docstring.
- This PR refactors the `user_journeys.utils.API` class to wait for responses from the …

Add user journey for logging in and deleting shared environment

---

.github/workflows/tests.yaml
conda-store-server/pyproject.toml
conda-store/environment.yaml
conda-store/pyproject.toml

Split from #792 
- **BumpJLab** - now conda-store-ui is JLab >= 4.0 compatible
- **Update dev and runtime dependencies - server**
- **Update runtime dependencies - core**
- **Update dev dependencies - core**
This can be tested by building the packages with `hatch build` both for `conda-store` and `conda-store-server`

MAINT - Add conda-store dependencies to pyproject.toml

---

conda-store-server/tests/user_journeys/test_data/broken_environment.yaml
conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

Fixes #672.
This PR implements a user journey test that checks that a user can access logs for a failed build.
- Adds a simple broken environment spec
- Implements a `get_logs` function for the user journey API utils
- Adds a test for the user journey mentioned above
Run the conda-store server:
```bash
docker compose up
```
Then run the test:
```bash
pytest tests/user_journeys/test_user_journeys.py::test_failed_build_logs
```

Add user journey test to check that logs can be found for failed builds

---

.github/workflows/conda.yml
.github/workflows/release.yaml
recipe/meta.yaml

(Part of a conversation with @trallard)
- Adds `recipe/` with a couple minor fixes (to be contributed to conda-forge)
- Adds a Release workflow step depending on a new action https://github.com/jaimergp/conda-build-action
- Together this all ensures the conda dependencies are in sync with the Python ones 
This is a CI change, so it's a matter of making the CI pass. That said, one can run `conda build recipe` in different OSs to get a feeling.

Add conda recipe with verification workflow

---

conda-store-server/tests/user_journeys/test_data/simple_environment2.yaml
conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

Fixes #671.
This PR adds a user journey test which checks that an admin can activate an old build for a given environment.
- Adds a user journey test
- Adds a new test environment needed for the test: `simple_environment2.yaml`
Run the conda-store server:
```bash
docker compose up
```
Then run the test:
```bash
pytest tests/user_journeys/test_user_journeys.py::test_admin_set_active_build
```

Add user journey test to mark build as active

---

conda-store-server/conda_store_server/__init__.py
conda-store-server/environment-dev.yaml
conda-store-server/environment-macos-dev.yaml
conda-store-server/environment-windows-dev.yaml
conda-store-server/environment.yaml
conda-store-server/pyproject.toml
conda-store-server/tests/test_server.py
docusaurus-docs/conda-store/references/configuration-options.md

Fixes #648.
- sets `CONDA_STORE_DIR` to `platformdirs.user_data_path`
- updates docs
- adds a test.

Set `CONDA_STORE_DIR` to `platformdirs.user_data_path`

---

docusaurus-docs/src/css/custom.css
docusaurus-docs/src/pages/index.js

Fixes #764
This pull request updates the documentation theme properties with the conda-store theme.
Currently, this is a draft PR to have a preview as we make updates.
Add @smeragoel as a co-author while merging.

Update docs theme

---

conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/build.py

Currently the `conda_flags` parameter in https://github.com/conda-incubator/conda-store/blob/2024.3.1/conda-store-server/conda_store_server/action/generate_lockfile.py#L20 but this is not configurable.
This PR includes changes to have the `conda_flags` parameter configurable from the config py script.
We are using conda-store within nebari in one of our projects. We have a reason why we don't need strict channel priority while building the environments. The default is still `--strict-channel-priority` to be backwards compatible, but it makes the option to the user to configure different conda flags e.g. `--no-channel-priority`.
- running tests locally
- was deployed and tested with nebari on a k8s cloud
Add e.g. `c.CondaStore.conda_flags = "--no-channel-priority"` in the config py script.

Make conda_flags configurable

---

conda-store-server/tests/user_journeys/test_data/complicated_environment.yaml
conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

Fixes #674.
This PR adds a user journey test for canceling a build.
- Adds a new user journey test
- Refactors some of `api_utils.py` to use a new `wait_for_condition` function to poll the conda-store-server
Run the conda-store server:
```bash
docker compose up
```
Then run the test:
```bash
pytest tests/user_journeys/test_user_journeys.py::test_cancel_build
```

Add user journey test for canceling a build

---

conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

Fixes #673.
This PR adds a user journey test to add a lockfile for a build. Depends on #804, so I'll mark this as a draft until that one is merged.
- Adds a user journey test for getting a lockfile for a successful build as an admin user, and checking that it contains the expected dependencies.
- Adds a function to `api_utils.py` to retrieve the lockfile from the conda-store server
Run the conda-store server:
```bash
docker compose up
```
Then run the test:
```bash
pytest tests/user_journeys/test_user_journeys.py::test_get_lockfile
```

Add user journey test to retrieve a lockfile for a build

---

conda-store-server/conda_store_server/action/base.py
conda-store-server/conda_store_server/action/generate_constructor_installer.py
conda-store-server/conda_store_server/action/generate_lockfile.py
conda-store-server/conda_store_server/action/install_lockfile.py
conda-store-server/conda_store_server/action/utils.py
conda-store-server/conda_store_server/build.py
conda-store-server/conda_store_server/storage.py

Fixes #809.
- makes actions write to log storage incrementally: the output can be seen by users as soon as it's available
- changes the logging format by prefixing each line with the name of the action: makes it easier to see what code is running
- adds locking when appending to logs to avoid a race condition
- moves the body of `logged_command` to `ActionContext.run_command`, next to `run`.
- start an environment build
- go to the logs page for this build
- check that new output appears while an action is running, by refreshing the page quickly
- check that all output is prefixed with the action name

Implement log flushing

---

conda-store-server/environment.yaml
conda-store-server/pyproject.toml
conda-store/environment.yaml
conda-store/pyproject.toml

This PR updates runtime dependencies in preparation for the upcoming release.
See #801 for the related PR that this one was based on. The only difference between the dependencies changed here and the ones in that PR is that I removed `pytest-mock`, which isn't being used as far as I can tell.

Update runtime dependencies

---

.github/workflows/test_build_docker_image.yaml
.github/workflows/test_conda_store.yaml
.github/workflows/test_conda_store_server_integration.yaml
.github/workflows/test_conda_store_server_unit.yaml
.gitignore
recipe/meta.yaml

Since the CI takes so long, it does not make sense to run all the CI workflows when making docs-only changes.
This PR:
- **:construction_worker: CI should not run on docs**
- **:wrench: Update conda recipe** (forgot to update it recently when I updated the feedstock; please do not hate me)

ENH - Update workflows triggers

---

.github/workflows/test_build_docker_image.yaml
.github/workflows/test_conda_store.yaml
.github/workflows/test_conda_store_server_integration.yaml
.github/workflows/test_conda_store_server_unit.yaml
conda-store-server/pyproject.toml
recipe/meta.yaml

It seems the triggers updates in #832  are not currently working using the `!` ignore pattern in paths.
This PR changes such triggers to an explicit `include` paths pattern.
🚨 The build conda package workflow will fail until we merge #836

BUG - Fix triggers

---

docker-compose.yaml

Fixes #825.
This PR removes the deprecated `version` option from `docker-compose.yml` to avoid raising a warning every time you use it.

[MAINT] Remove deprecated docker-compose config option

---

.gitignore
conda-store-server/tests/conftest.py

Fixes #849.
`CondaStoreWorker` instances subclass `traitlets.Application`. `traitlets` can parse `sys.argv` to set configuration variables for the application. In certain situations e.g. running `pytest -svv`, the worker initializes and immediately tries to parse `-svv` as a `traitlets` configuration variable, which of course does not exist.
This PR fixes the `conda_store_config` fixture, which incorrectly manipulates `sys.argv`, and inadvertently allows pytest args to get parsed as `traitlets` configuration settings.
---
Other minor change: updated the `.gitignore` to include `conda-store-ui` static files, which I missed when the privatization PR went through.
Here's the original offending pytest invocation, which now works as intended:
```bash
pytest …
```

[MAINT] Prevent workers from trying to parse sys.argv upon intialization

---

.github/workflows/generate_api_docs.yaml

This pull request adds the complete file path to the `openapi.json` file `generate_api_docs.yaml` GitHub Action.
This path is used in a `git add` in the action. The incomplete path results in [`Error: Error: fatal: pathspec 'openapi.json' did not match any files`](https://github.com/conda-incubator/conda-store/actions/runs/10371150640/job/28710757374?pr=861#step:6:23)
Thanks for surfacing the issue, @trallard!
xref: #782 
I don't think there is a quick way to test this, besides testing on a fork.

Update `openapi.json` file path in `generate_api_docs.yaml`

---

.github/workflows/generate_api_docs.yaml
docusaurus-docs/static/openapi.json

Fixes #870.
This pull request runs `jq` to format the generated `openapi.json` in a more human readable format. This also inserts a newline at the end of the file so that `pre-commit.ci` stops failing on all PRs.
I've also made `jq` sort the json by keys, which should make the order nice and stable.

[MAINT] Make github workflow format openapi.json

---

conda-store-server/Dockerfile
conda-store/Dockerfile

Fixes https://github.com/conda-incubator/conda-store/issues/882.
Update image to get access to latest conda with libmamba as default solver

update to latest miniforge image

---

conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html

Properly sets the logout url when using the integrated ui.
Fixes https://github.com/nebari-dev/nebari/issues/2717 
Currently, using the `c.CondaStoreServer.enable_ui = True` configuration option uses conda-store-ui with the following config:
```python
var condaStoreConfig = {
NODE_DEBUG: null,
REACT_APP_CONTEXT: "single-page-app", // not a true setting
REACT_APP_AUTH_METHOD: "cookie",
REACT_APP_AUTH_TOKEN: "",
REACT_APP_STYLE_TYPE: "green-accent",
REACT_APP_SHOW_LOGIN_ICON: "true",
REACT_APP_API_URL: "{{ url_for('get_conda_store_ui') }}",
REACT_APP_LOGIN_PAGE_URL: "{{ url_for('get_login_method') }}?next=",
};
```
The fact that the logout url is not set results in logout not working. We can see in https://nebari.quansight.dev/conda-store/ that the logout route is set to the default value. …

Set logout url properly when using the integrated ui

---

.github/workflows/generate_api_docs.yaml

Fixes #888.
Apparently `github.event.pull_request.head.ref` isn't always guaranteed to exist on pull requests. The docs for `EndBug/add-and-commit` suggest using this ref because otherwise the branch is checked out in a detached head state. A simple search for "how to add and commit in github actions" turns up a bunch of results that suggest that in fact you can just call `actions/checkout` and then `git add .; git commit -m <message>; git push`, so I'm not really sure who is right. The PR tests out the second approach.
This PR doesn't actually trigger the workflow that updates openapi.json, but I've been trying it on https://github.com/conda-incubator/conda-store/pull/881:
1. Checking out with the `github.event.pull_request.head.ref`, which doesn't exist sometimes:
```yaml
- name: …
```

[BUG] Fix openapi.json generation workflow

---

conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html

Companion PR to https://github.com/conda-incubator/conda-store-ui/pull/431

REACT_APP_URL_BASENAME

---

conda-store-server/Dockerfile

Previously, when running `docker compose up -d` the worker container would have some errors output because it is not able to create it's celery beat file. For example,
```
$ docker compose up 
. . .
conda-store-worker-1  | [2024-10-19 00:44:41,925: INFO/Beat] beat: Starting...
conda-store-worker-1  | [2024-10-19 00:44:41,952: ERROR/Beat] Removing corrupted schedule file '/.local/share/conda-store/celerybeat-schedule': FileNotFoundError(2, 'No such file or directory')
. . .
conda-store-worker-1  | [2024-10-19 00:44:41,967: WARNING/Beat] FileNotFoundError: [Errno 2] No such file or directory: b'/.local/share/conda-store/celerybeat-schedule.dat'
. . .
```
This PR creates the missing directory and gives the user permission to it so celery can create it's beat file. Now the output is:
```
$ …
```

Create local conda-store dir for celery beat data files

---

.github/ISSUE_TEMPLATE/new-release.md
conda-store-server/Dockerfile
conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html
docker-compose.ui.yaml

There is no issue associated with this PR but this should help us with verifying how we are vendoring the UI (and the conda-store releases)
I will update the docs once someone else verifies this. 
1. You will need to have a local fork of `conda-store-ui` and create a bundle:
```bash
yarn run build
yarn run webpack:prod bundle
```
2. On the `conda-store` repository:
```bash
export LOCAL_UI=<path-to-the-root-of-the-ui-dir>  && hatch build
4. Start the conda-store-instances:
```bash
docker compose -f docker-compose.ui.yaml up --build
```
Head to localhost:8080 when ready, if built against main the version displayed on the UI should be `"2024.9.2-rc1"`

DEV - Extend compose to include target for local UI

---

conda-store-server/conda_store_server/_internal/server/views/api.py

Fixes #615 and #761 
The `GET /specification` endpoint is meant to allow users to specify some conda environment configuration (packages, channels, etc) and return the set of packages for the solved environment.
Previously, this endpoint was broken
```
$ curl http://localhost:5000/conda-store/api/v1/specification/
Internal Server Error
```
With this change, users can use the endpoint 
```
$ curl http://localhost:5000/conda-store/api/v1/specification/
{"solve":[{"id":117414,"channel_id":2,"build_number" .... 
```

Wait for celery to return response to request to solve specification

---

conda-store-server/conda_store_server/_internal/worker/app.py

This small PR updates the conda store worker to respect the `CondaStoreWorker.log_level` config parameter. Now users can see that the log level set for their works gets applied to the worker.
Before this change, the worker was always running at `logger.INFO` log level. For example, you can see in the log output
```
. . .
conda-store-worker-1  | [2024-10-19 01:41:55,960: INFO/MainProcess] Connected to redis://:**@redis:6379/0
conda-store-worker-1  | [2024-10-19 01:41:55,962: WARNING/MainProcess] /opt/conda/envs/conda-store-server/lib/python3.12/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
```
To test this add the following line to your conda-store config file
``` …
```

Respect worker log level config setting

---

conda-store-server/pyproject.toml

Fixes #915.
This pull request pins `pyyaml==5.3.1` due to an incompatibility with `cython>=3`, which is a transitive dependency of this project.
@soapy1 Would you be willing to check that this works for you? It's enough to run tests and then `hatch shell dev` inside `conda-store-server/`.

[BUG] Pin pyyaml dependency due to cython>=3 incompatibility

---

.github/workflows/test_conda_store_server_unit.yaml
conda-store-server/environment-dev.yaml
conda-store-server/pyproject.toml

partially addresses https://github.com/conda-incubator/conda-store/issues/914
This change addresses the code coverage visibility issue in #914. It enables:
* generating coverage stats when running unit tests
* reporting code coverage results in the github action

Add coverage report to unit tests

---

conda-store-server/tests/_internal/worker/__init__.py
conda-store-server/tests/_internal/worker/test_app.py
conda-store-server/tests/conftest.py
conda-store-server/tests/test_storage.py

partially fixes https://github.com/conda-incubator/conda-store/issues/914
This PR adds a few unit tests to try to improve the code coverage. Tests covered:
* storage 
* storage local
* starting conda-store-worker

Add tests - storage + worker

---

conda-store-server/conda_store_server/_internal/server/app.py

Fixes # https://github.com/conda-incubator/conda-store/issues/516
(along with https://github.com/conda-incubator/conda-store/pull/903)
This change ensures that the log level set by the `CondaStoreServer.log_level` config gets applied to the uvicorn server. The default behaviour remains the same, that is, the log level is set to `INFO` by default ([this is the default by uvicorn ](https://www.uvicorn.org/settings/#logging)when the log_level is not set).
To test this out, try running a conda-store server with the following configs:
See info level logging (currently, the only option)
```
c.CondaStoreServer.log_level = logging.INFO
```
See critical level logging (pretty much no logs output)
```
c.CondaStoreServer.log_level = logging.CRITICAL
```

Make conda-store server launch uvicorn with log level

---

docusaurus-docs/community/roadmap.md

This pull request updates the roadmap:
- Explicitly adds an item for making a plugin system for locking, solving, and package management
- Adds links to issues for a number of items that were missing them

[DOC] Roadmap updates

---

docusaurus-docs/conda-store/how-tos/install-kubernetes.md
examples/kubernetes/conda-store-server.yaml
examples/kubernetes/conda-store-worker.yaml

Currently, the k8's example is running an outdated version of conda store. To provide a more current/relevant setup, update the container images to the latest release `2024.10.1`

Bump k8 example version

---

conda-store-server/conda_store_server/_internal/server/app.py
conda-store-server/conda_store_server/_internal/worker/app.py

Fixes https://github.com/conda-incubator/conda-store/issues/977
This pr set's up the traitlets application to know the current version of conda-store. Setting the version property of a traitlets Application will allow the built in trailtlets '--version' flag to work properly.
For example, running `conda-store-server --version` now works properly
```
$ conda-store-server --version 
2024.11.1
$ conda-store-worker --version
2024.11.1
```
ref:
https://github.com/ipython/traitlets/blob/main/traitlets/config/application.py#L872
https://github.com/ipython/traitlets/blob/main/traitlets/config/application.py#L200

DEV - Set traitlets application version

---

conda-store-server/conda_store_server/_internal/orm.py
conda-store-server/tests/_internal/test_orm.py

related to https://github.com/conda-incubator/conda-store/issues/852
Previously, whenever the packages for a channel would get updated, duplicated packages across channels would cause an sql error.
```
conda-store-worker-1  | (Background on this error at: https://sqlalche.me/e/14/gkpj)
conda-store-worker-1  | [2024-11-07 05:27:06,310: ERROR/ForkPoolWorker-5] Task task_update_conda_channel[73d1f6c4-e39e-4d77-a73d-0a61c5824648] raised unexpected: IntegrityError('(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "_conda_package_build_uc"\nDETAIL:  Key (channel_id, package_id, subdir, build, build_number, sha256)=(3, 5618, linux-64, py27_0, 0, d65b4ca2fa3e2e9f6dc84b4883255c395a381bb11a3009c2f6fefa24aa284db8) already exists.\n')
conda-store-worker-1  | Traceback …
```

Update conda-package-build causes an integrity error on conda_package_build table

---

conda-store-server/conda_store_server/_internal/orm.py

This should be a string instead of an int, for example "py310h06a4308_0". This was probably updated to the wrong type by accident as part of https://github.com/conda-incubator/conda-store/pull/970

Fix conda_package_build "build" column type

---

.github/ISSUE_TEMPLATE/new-release.md
cut-release-pr.sh

This PR proposes a script to automate some manual steps of the current release process. Used this script to cut the latest release (2024.11.2) and it made things go pretty quick and smooth.
Note, this is not a replacement for #861 or #911, we should definitely still do those.
You can test out running this script by (following the setup instructions and then) running
```
$ ./cut-release-pr.sh -r release_version -c conda_store_ui_version
```
This will:
* create a new branch `release-<release_version>`
* put you on that branch
* update the versions of conda-store, conda-store-server, conda-store-ui 
* update the changelog using the `github-activity` tool
* use hatch to build and check the package version
* use twine to check the validity of the package
* commit the changes to your branch …

Release helper script

---

.github/workflows/test_conda_store_server_unit.yaml

Currently we run integration tests on all supported python versions. We should do the same with unit tests.

Run unit tests on all supported python versions

---

conda-store-server/conda_store_server/_internal/environment.py
conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
conda-store-server/conda_store_server/_internal/schema.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/conda_store_ui.py
conda-store-server/conda_store_server/_internal/server/views/ui.py
conda-store-server/conda_store_server/_internal/worker/build.py
conda-store-server/conda_store_server/app.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/tests/_internal/action/test_actions.py
conda-store-server/tests/_internal/server/views/test_api.py
conda-store-server/tests/_internal/test_schema.py
conda-store-server/tests/conftest.py
tests/test_api.py

There are currently lots of deprecation warning when running the test suite. Some of them come from upstream dependencies. But many are from conda-store. This PR aims to resolve some of them.
not fixed:
* `datetime.datetime.utcnow` is deprecated, should be replaced with `datetime.datetime.now(datetime.UTC)`. However, this is not supported by python 3.10. Will address this when we drop python 3.10 support

Fix deprecation warnings

---

conda-store-server/conda_store_server/_internal/server/templates/user.html
conda-store-server/conda_store_server/_internal/server/views/ui.py

- Add default values for system metrics when None
- Add conditional system metrics display in template
- Show informative message when metrics unavailable
Closes #1028

fix: handle None system metrics in user admin panel

---

.gitignore
conda-store-server/conda_store_server/_internal/alembic/script.py.mako
conda-store-server/conda_store_server/_internal/alembic/versions/89637f546129_remove_conda_package_build_channel.py
conda-store-server/conda_store_server/_internal/orm.py
conda-store-server/environment-dev.yaml
conda-store-server/pyproject.toml
conda-store-server/tests/_internal/alembic/__init__.py
conda-store-server/tests/_internal/alembic/version/__init__.py
conda-store-server/tests/_internal/alembic/version/test_89637f546129_remove_conda_package_build_channel.py
conda-store-server/tests/_internal/test_orm.py
conda-store-server/tests/conftest.py
docusaurus-docs/conda-store/references/database.md

Fixes https://github.com/conda-incubator/conda-store/issues/994
The primary focus of this pr is to remove the `channel_id` column and `channel` association in the `conda_package_build` table. This is redundant information, also available in the associated `package`. In order to get channel information from a `conda_package_build` users may join the `conda_package` table and `conda_package_build` table. For example:
```
from conda_store_server._internal import orm
db.query(orm.CondaPackageBuild)
.join(orm.CondaPackage)
.filter(orm.CondaPackage.channel_id == 1)
```
Things changed in this PR:
* removal of the `channel_id` column in the `conda_package_build` table
* a migration script. It does 2 things:
*  updates the `conda_package_build` to have the correct package associated with each row. …

Remove redundant channel column

---

conda-store-server/conda_store_server/_internal/orm.py
conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
conda-store-server/conda_store_server/_internal/server/app.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/ui.py
conda-store-server/conda_store_server/_internal/worker/app.py
conda-store-server/conda_store_server/_internal/worker/tasks.py
conda-store-server/conda_store_server/conda_store.py
conda-store-server/conda_store_server/conda_store_config.py
conda-store-server/tests/_internal/action/test_actions.py
conda-store-server/tests/_internal/plugins/lock/test_conda_lock.py
conda-store-server/tests/_internal/worker/test_app.py
conda-store-server/tests/conftest.py
conda-store-server/tests/test_api.py
conda-store-server/tests/test_conda_store.py
conda-store-server/tests/test_conda_store_config.py

pre req for resolving https://github.com/conda-incubator/conda-store/issues/1005
This PR refactors `conda_store_server/app.py` to split the config portion and app instance portion of the class. The goal of this refactor is more clearly delineate responsibility between the 2 classes/pieces of functionality. Eventually, this should also make how to approach changes to the config more clear.
2 new objects are introduced:
* `conda_store_config:CondaStore`
* this is the config class for conda store
* it uses traitlets to get config
* it's only responsibility is to read the config file and provide that info to `conda_store:CondaStore`
* `conda_store:CondaStore`
*  this has common app functions like `get_settings`, `set_settings`, etc
* it gets it's configuration from …

Separate conda-store app instance from config

---

conda-store-server/tests/_internal/test_utils.py

This test started failing due to a difference in how `du` works on ubuntu 24.04 (the new `ubuntu-latest` version in GHA) and ubuntu 22.04. See the following example:
```
(conda-store-server-dev) sophia:conda-store-server/ (test_disk_usage-test✗) $ docker run -i
t ubuntu:24.04
Unable to find image 'ubuntu:24.04' locally
24.04: Pulling from library/ubuntu
de44b265507a: Pull complete 
Digest: sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab
Status: Downloaded newer image for ubuntu:24.04
root@55628d140146:/# mkdir /test
root@55628d140146:/# du -sb test/
0       test/
root@55628d140146:/# 
exit
(conda-store-server-dev) sophia:conda-store-server/ (test_disk_usage-test✗) $ docker run -it ubuntu:22.04
Unable to find image 'ubuntu:22.04' locally
22.04: Pulling from …
```

Update test_disk_usage for change in default `du` behaviour in ubuntu 24.04

---

conda-store-server/tests/conftest.py

https://github.com/conda-incubator/conda-store/pull/1023 introduced splitting conda store config from the conda store class. This pr updates tests that got left out.

Get database url from conda-store config in tests

---

conda-store-server/conda_store_server/_internal/server/app.py

Errors will already be printed to the console if the log level is set to `DEBUG`.
Having this exception handler catch all exceptions and invoke the http_exception_handler is incorrect behaviour. This causes the http_exception_handler to be called for non HTTPExceptions. Since the exception passed in is the wrong type, this often causes a new exception to be triggered.
For example, when handling a non HTTPException, this will be in the error message
```
conda-store-server-1  | Traceback (most recent call last):
conda-store-server-1  |   File "/opt/conda/envs/conda-store-server/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
conda-store-server-1  |     result = await app(  # type: ignore[func-returns-value]
conda-store-server-1  | …
```

Remove exception handler that prints to the console

---

conda-store-server/conda_store_server/_internal/server/templates/login.html
conda-store-server/conda_store_server/server/auth.py
conda-store-server/tests/conftest.py
conda-store-server/tests/server/test_auth.py
tests/test_playwright.py

Fixes https://github.com/conda-incubator/conda-store/issues/1034
This PR updates the auth module to be agnostic to the admin ui. It does this by:
* separating the login page from the `base.html` template
* removing references to admin ui endpoints from the auth module

Login page without UI enabled

---

conda-store-server/conda_store_server/_internal/environment.py
conda-store-server/conda_store_server/_internal/orm.py
conda-store-server/conda_store_server/_internal/schema.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/registry.py
conda-store-server/conda_store_server/_internal/server/views/ui.py
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/conda_store.py
conda-store-server/conda_store_server/conda_store_config.py
conda-store-server/conda_store_server/server/auth.py
conda-store-server/conda_store_server/server/schema.py
conda-store-server/tests/_internal/server/views/test_api.py
conda-store-server/tests/server/test_auth.py
docusaurus-docs/conda-store/references/auth.md
tests/test_api.py

Fixes https://github.com/conda-incubator/conda-store/issues/1042
This will allow users to define their own auth modules without dependings on internal schemas. 
In particular this enables nebari to not depend on the `conda_store_server._internal.schema` module for setting up the keycloak auth backend (ref. https://github.com/nebari-dev/nebari/blob/f39467679ce2dac84385f1d6d4ec698befd7c126/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py#L14).
This is intended as a stop gap solution until [conda-store support authentication plugins](https://github.com/conda-incubator/conda-store/issues/1031). As such, this PR aims to not make any changes that will make it more difficult to move towards auth plugins.

Move auth related schema to inside the auth module

---

conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
conda-store-server/conda_store_server/_internal/server/app.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/ui.py
conda-store-server/conda_store_server/_internal/settings.py
conda-store-server/conda_store_server/_internal/worker/build.py
conda-store-server/conda_store_server/_internal/worker/tasks.py
conda-store-server/conda_store_server/api.py
conda-store-server/conda_store_server/conda_store.py
conda-store-server/conda_store_server/conda_store_config.py
conda-store-server/pyproject.toml
conda-store-server/tests/_internal/server/views/test_api.py
conda-store-server/tests/_internal/test_settings.py
conda-store-server/tests/conftest.py
conda-store-server/tests/test_api.py
conda-store-server/tests/test_conda_store_config.py
docusaurus-docs/conda-store/references/configuring-conda-store.md

Fixes https://github.com/conda-incubator/conda-store/issues/1005
This PR introduces a settings module for interacting with conda store settings. It also adds some documentation and enforces rules for how settings get merged at each of the different levels of abstraction that setting apply to. 
There are multiple levels which settings config can be applied to conda store. 
* deployment defaults (controlled by the config file)
* global defaults (controlled by the admin console)
* namespace defaults (controlled by the admin console)
* environment default (controlled by the admin console)
The most specific settings config will take precedence over the more  general setting.
The introduction of this settings object will allow:
* defining a common pattern for accessing settings
* enforcing …

Add settings module

---

conda-store-server/tests/user_journeys/test_user_journeys.py
conda-store-server/tests/user_journeys/utils/api_utils.py

This PR makes a variety of fixes to the user journey tests in order to run them against non default targets (eg. like nebari's conda store deployment). This is required for https://github.com/nebari-dev/nebari/pull/2895
Previously setting any value for `CONDA_STORE_TEST_VERIFY_SSL`  resulted in enabling ssl verification. So, setting `CONDA_STORE_TEST_VERIFY_SSL=0` or `CONDA_STORE_TEST_VERIFY_SSL=false` enabled ssl verification. This is because strings are truthy. 
This PR fixes this by checking if the passed in env var is one of `0`, `false` or `False` in order to determine if tests should verify SSL.
Previously all but one conda-store user journey tests used the `CONDA_STORE_TOKEN` as auth when running tests. This PR extends this so that all user journey tests can use the provided auth …

Fix user-journey tests for running against non-default targets

---

conda-store/pyproject.toml

Fixes https://github.com/conda-incubator/conda-store/issues/1053
The conda-store (cli) package does not have dependencies on jupyter - cleaning up these dependencies. 
For reference, you can also check against the conda package recipe https://github.com/conda-incubator/conda-store/blob/main/recipe/meta.yaml#L34-L43 (which does not express any dependencies on jupyter).

Trim conda-store package dependencies

---

conda-store-server/conda_store_server/_internal/settings.py
conda-store-server/conda_store_server/_internal/worker/tasks.py
conda-store-server/conda_store_server/conda_store.py
conda-store-server/conda_store_server/conda_store_config.py

Follow up to https://github.com/conda-incubator/conda-store/pull/1044
It ensures that there is consistency in how settings are retrieved throughout the code base and ensures that settings are pulled at the right specificity.

Ensure settings are retrieved for the right level

---

conda-store-server/conda_store_server/_internal/server/app.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/registry.py
conda-store-server/tests/_internal/server/views/test_api.py
docusaurus-docs/conda-store/explanations/artifacts.md
docusaurus-docs/conda-store/references/configuration-options.md
examples/docker-without-nfs/assets/conda_store_config.py
examples/docker/assets/conda_store_config.py
examples/kubernetes/files/conda_store_config.py
examples/ubuntu2004/templates/conda_store_config.py.j2
tests/assets/conda_store_config.py

fixes https://github.com/conda-incubator/conda-store/issues/942
This aims to start the process of removing the `/registry` endpoint. It:
* disables the registry endpoint by default
* adds deprecation headers to all the endpoints under `/registry`
* target deprecation date March 17, 2025

Deprecate docker registry

---

.github/workflows/release.yaml

Fixes https://github.com/conda-incubator/conda-store/issues/1043
Currently we build and release docker images for amd64 and arm64 platforms on each merge to main, but do not release arm64 images on releases.
This PR will update the release process to also ship arm64 docker images.

Build and release a arm64 docker image as part of the release process

---

conda-store-server/conda_store_server/_internal/schema.py
conda-store-server/tests/_internal/server/views/test_api.py
conda-store-server/tests/conftest.py

Fixes https://github.com/conda-incubator/conda-store/issues/1062
This PR updates the pydantic model for `Namespace` so that the `metadata_` field can be null. This field is nullable, and the default value is an empty dict:
```
class Namespace(Base):
"""Namespace for resources"""
. . .
metadata_: Mapped[Optional[dict]] = mapped_column(JSON, default=dict, nullable=True)
. . .
```
In order for pydantic models to allow values to be `None`, they must set them as `Optional`. If not, an error will be thrown. 
In older deployments on conda-store it is possible for this field to actually be `NULL` (see the explanation https://github.com/conda-incubator/conda-store/issues/1062#issuecomment-2622435285), resulting in an error.
While sorting this out I also checked for other orm fields that were …

Allow Namespace pydantic model to have a null metadata_ entry

---

.github/ISSUE_TEMPLATE/new-release.md
conda-store-server/conda_store_server/__init__.py
conda-store/conda_store/__init__.py

* bumps dev version after release  to `2025.1.2-dev`
* updates the `release` github issue type for small changes in the release process
* no longer need to bump the conda-store version in the conda-store-ui repo (https://github.com/conda-incubator/conda-store-ui/pull/448)
* the `cut-release` script is in the `tools/` dir (https://github.com/conda-incubator/conda-store/pull/1027)

Bump dev version

---

conda-store-server/conda_store_server/conda_store_config.py

This PR fixes an instance where `utils.CondaStoreError` was being called, when that exception class has been moved.

[BUG] Fix bad invocation of CondaStoreError

---

conda-store-server/conda_store_server/_internal/server/app.py
conda-store-server/conda_store_server/_internal/server/views/api.py
conda-store-server/conda_store_server/_internal/server/views/registry.py
conda-store-server/tests/_internal/server/views/test_api.py

This PR deprecates the `/api/v1/environments/` endpoint, which has been replaced with cursor-based pagination in `/api/v2/environments/`.

[MAINT] Deprecate `/api/v1/environments/`

---

docker-compose.yaml

This PR mounts the conda-store code into the running docker containers. So, if you are iterating on server side code, your changes will automatically get picked up (and the server will reload with hot reloading).
This require devs to have conda-store-ui vendored. This can be done
```
$ cd conda-store-server
$ hatch build
```
Users can also run against a particular version of the ui
```
$  LOCAL_UI=/home/sophia/projects/conda-store-ui hatch build
```

Mount code into docker container

---

conda-store-server/conda_store_server/_internal/schema.py
conda-store-server/tests/_internal/test_schema.py

Fixes https://github.com/conda-incubator/conda-store/issues/1085
This PR re-adds the `DOCKER_BLOB` build artifact enum value. This is required for backwards compatibility with old database entries.
* insert a new build into the database with the `docker_blob` artifact type
one way to do this is to add a new artifact to an existing build. For example (with the docker compose setup):
```
$ docker compose exec -it psql
// see what build artifacts exist
conda-store=# select * from build_artifact;
id | build_id | artifact_type |                                  key                                   
----+----------+---------------+------------------------------------------------------------------------
1 |        1 | LOGS          | logs/c3457167-1739296499-1-python-flask-env.log
2 |        1 …
```

Re-add docker blob build artifact type
